// Static output is committed for GitHub Pages. app.js remains the menu master.
// No browser-side requests or additional runtime dependencies are introduced.
import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
const config = JSON.parse(await fs.readFile(path.join(root, 'seo.config.json'), 'utf8'));
// Keep this public verification token installed after Search Console verification.
if (!/^[A-Za-z0-9_-]+$/.test(config.googleSiteVerification ?? '')) {
  throw new Error('Search Console verification token is missing or invalid.');
}
const read = file => fs.readFile(path.join(root, file), 'utf8');
const escape = value => String(value).replace(/[&<>"']/g, char =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const app = await read('app.js');
const source = app.match(/const MENU=(\{[\s\S]*?\});/);
if (!source) throw new Error('Menu master not found; review app.js before generating.');
const menu = vm.runInNewContext('(' + source[1] + ')', Object.create(null), { timeout: 1000 });
const languages = { ja: 'ja', en: 'en', zh: 'zh-Hans', ko: 'ko' };
if (Object.keys(menu).join(',') !== Object.keys(languages).join(',')) {
  throw new Error('Menu languages changed; update the static menu generator.');
}
let html = await read('index.html');
html = html.replace(/<title>[^<]*<\/title>/, '<title>' + escape(config.title) + '</title>');
for (const [attribute, key, value] of [
  ['name', 'description', config.description],
  ['property', 'og:title', config.title],
  ['property', 'og:description', config.description],
  ['name', 'twitter:title', config.title],
  ['name', 'twitter:description', config.description],
]) {
  const pattern = new RegExp('<meta ' + attribute + '="' + key + '" content="[^"]*">');
  if (!pattern.test(html)) throw new Error('Missing metadata: ' + key);
  html = html.replace(pattern, '<meta ' + attribute + '="' + key + '" content="' + escape(value) + '">');
}
const absolute = file => new URL(file, config.url).href;
const restaurantId = config.url + '#restaurant';
const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': config.url + '#website',
      url: config.url,
      name: config.name,
      alternateName: 'AJIICHIBAN TSUBASA',
      inLanguage: 'ja',
      publisher: { '@id': restaurantId },
    },
    {
      '@type': 'WebPage',
      '@id': config.url + '#webpage',
      url: config.url,
      name: config.title,
      description: config.description,
      inLanguage: 'ja',
      isPartOf: { '@id': config.url + '#website' },
      mainEntity: { '@id': restaurantId },
    },
    {
      '@type': 'Restaurant',
      '@id': restaurantId,
      name: config.name,
      alternateName: 'AJIICHIBAN TSUBASA',
      url: config.url,
      telephone: config.telephone,
      address: config.address,
      servesCuisine: ['ラーメン', '味噌ラーメン'],
      image: ['assets/ultimate-miso.webp', 'assets/butter-corn.webp', 'assets/tsubasa-ramen.webp'].map(absolute),
      logo: absolute('assets/tsubasa-logo.png'),
      hasMenu: config.url + '#menu',
      openingHoursSpecification: config.openingHoursSpecification,
      specialOpeningHoursSpecification: config.specialOpeningHoursSpecification,
    },
  ],
};
const seo = [
  '<!-- SEO:START (generated by npm run build:seo) -->',
  '<link rel="canonical" href="' + escape(config.url) + '">',
  '<meta name="robots" content="index, follow, max-image-preview:large">',
  '<meta name="google-site-verification" content="' + escape(config.googleSiteVerification) + '">',
  '<script type="application/ld+json" id="restaurant-schema">',
  JSON.stringify(schema, null, 2).replace(/</g, '\\u003c'),
  '</script>',
  '<noscript><style>.reveal{opacity:1!important;transform:none!important}</style></noscript>',
  '<!-- SEO:END -->',
].join('\n');
if (html.includes('<!-- SEO:START')) {
  html = html.replace(/<!-- SEO:START[\s\S]*?<!-- SEO:END -->/, seo);
} else {
  html = html.replace('</head>', seo + '\n</head>');
}
for (const [lang, htmlLang] of Object.entries(languages)) {
  if (!Array.isArray(menu[lang]) || !menu[lang].length) throw new Error('Empty menu: ' + lang);
  const rows = menu[lang].map(([name, price], index) =>
    '<div class="menu-row' + (index >= 18 && index <= 20 ? ' menu-row-set' : '') +
    '"><b>' + escape(name) + '</b><span>' + escape(price) + '</span></div>').join('\n');
  const pattern = new RegExp('(<div class="menu-panel[^"]*" data-panel="' + lang +
    '")[^>]*><div class="menu-text-list"[^>]*>[\\s\\S]*?(?=<div class="menu-sheet-card">)');
  if (!pattern.test(html)) throw new Error('Missing static menu panel: ' + lang);
  html = html.replace(pattern, '$1 lang="' + htmlLang + '"><div class="menu-text-list" data-complete="40-item-master">\n' +
    rows + '\n</div>');
}
const outputs = new Map([
  ['index.html', html],
  ['robots.txt', 'User-agent: *\nAllow: /\n\nSitemap: ' + config.url + 'sitemap.xml\n'],
  ['sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    '  <url><loc>' + escape(config.url) + '</loc><lastmod>' + config.lastModified + '</lastmod></url>\n' +
    '</urlset>\n'],
]);
// Public engineering demos must not compete with the actual restaurant page.
// Keep them crawlable so search engines can see noindex (robots.txt is not a removal tool).
for (const directory of ['reference', 'steam-lab', 'steam-lab-live', 'progress']) {
  for (const file of await fs.readdir(path.join(root, directory))) {
    if (!file.endsWith('.html')) continue;
    const filename = directory + '/' + file;
    const original = await read(filename);
    const directive = '<meta name="robots" content="noindex, follow">';
    const updated = /<meta name="robots"[^>]*>/.test(original)
      ? original.replace(/<meta name="robots"[^>]*>/, directive)
      : original.replace('<head>', '<head>' + directive);
    if (!updated.includes(directive)) throw new Error('Missing head: ' + filename);
    outputs.set(filename, updated);
  }
}
const stale = [];
for (const [filename, content] of outputs) {
  const current = await read(filename).catch(error => {
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (current !== content) {
    if (check) stale.push(filename);
    else await fs.writeFile(path.join(root, filename), content);
  }
}
if (stale.length) throw new Error('SEO output is stale. Run npm run build:seo: ' + stale.join(', '));
console.log((check ? 'Verified' : 'Generated') + ': metadata, Restaurant schema, ' +
  Object.keys(menu).length + ' static menu languages, sitemap, robots and demo noindex.');
