// Read the existing public masters; no second editable price list.
import fs from 'node:fs/promises';
import vm from 'node:vm';
const root = new URL('../', import.meta.url);
const app = await fs.readFile(new URL('app.js', root), 'utf8');
const match = app.match(/const MENU=(\{[\s\S]*?\});/);
if (!match) throw new Error('Menu master not found');
const menu = vm.runInNewContext(`(${match[1]})`, Object.create(null), {timeout:1000}).ja;
const shop = JSON.parse(await fs.readFile(new URL('seo.config.json',root),'utf8'));
const output = '// Generated by npm run build:ai from app.js and seo.config.json.\nexport default ' + JSON.stringify({menu,shop},null,2) + ';\n';
const file = new URL('ai/tsubasa-public-data.js',root);
if(process.argv.includes('--check')) {
 if(await fs.readFile(file,'utf8') !== output) throw new Error('AI data outdated: run npm run build:ai');
} else await fs.writeFile(file,output);
