// Editorial content: confirmed facts from the official site, not keyword variants.
// Prices and menu names come from app.js through build-seo.mjs.
export const locales = {
  ja: {
    path: 'menu/', lang: 'ja', label: '日本語', locale: 'ja_JP',
    title: 'メニュー・値段｜すすきのの味噌・バターコーンラーメン｜味一番つばさ',
    description: '味一番つばさの公式メニューと値段。究極の味噌1,100円、バターコーン、いくら丼とハーフラーメンのセットなど全40項目を掲載。札幌すすきの・新ラーメン横丁で11時から翌3時まで、月曜定休。',
    h1: 'つばさのメニュー。\nすすきので、一杯。', sub: 'メニュー・値段',
    intro: '味一番つばさのメニューを、味噌・醤油・塩から選べます。昼のランチにも、すすきのの夜を締めくくるラーメンにも。',
    home: '公式トップ', skip: '本文へ', menu: 'メニュー', access: '営業時間・行き方',
    viewMenu: '全メニューと値段を見る', signatures: 'つばさの三つの定番',
    dishText: ['三日間煮込んだスープ、特注麺、トロトロチャーシュー。つばさの原点となる味噌ラーメンです。', 'バターとコーンを合わせた一杯。味噌・醤油・塩の3種類からお選びいただけます。', 'いくら丼とハーフラーメンを一度に楽しめるセット。ラーメンだけでなく、ご飯ものも食べたいときに。'],
    dishTitles: ['究極の味噌ラーメン', 'バターコーンラーメン', 'つばさラーメン'],
    flavors: ['味噌', '醤油', '塩'], groups: ['味噌ラーメン', '醤油ラーメン', '塩ラーメン', 'セット・期間限定・ハーフ', '大盛り・トッピング', 'ご飯もの・餃子・お土産', 'お飲み物'],
    all: '全メニュー・価格', priceNote: '価格は日本円です。期間限定メニューの提供状況は店頭でご確認ください。',
    visitTitle: '11時から、翌3時まで。', hours: '営業時間 11:00〜翌03:00 ／ 毎週月曜日定休',
    address: '札幌市中央区南4条西3丁目1-1 第3グリーンビル 新ラーメン横丁',
    route: 'すすきの交差点から徒歩約1分。新ラーメン横丁内の「味一番つばさ」へお越しください。',
    maps: 'Google マップで徒歩ルート', call: '電話で問い合わせる',
    notice: 'シルバーウィーク：2026年9月21日（月）は営業、9月24日（木）は振替休業です。',
    qa: '来店前によくあるご質問',
    faqs: [
      ['味噌以外のラーメンはありますか？', '醤油・塩もあります。バターコーン、チャーシュー、ねぎ、キムチなどの種類と価格は上のメニュー一覧で確認できます。'],
      ['小さめのラーメンやご飯ものはありますか？', 'お子様ハーフは味噌・醤油・塩をご用意しています。いくら丼とハーフラーメンの「つばさラーメン」、チャーハン、ライスもあります。'],
      ['何時まで営業していますか？', '通常は11:00から翌03:00まで、毎週月曜日が定休日です。臨時の営業変更は公式サイトのお知らせをご確認ください。'],
      ['外国語でメニューを読めますか？', 'このページの言語リンクから、英語・中国語（簡体字）・韓国語で料理名と価格を確認できます。'],
      ['アレルギーや食材の相談はできますか？', 'アレルギーや食事制限がある方は、注文前に必ず店舗へご相談ください。このメニューだけで対応可否を判断しないでください。'],
    ],
    footer: '札幌すすきの・新ラーメン横丁のラーメン店。',
  },
  en: {
    path: 'en/', lang: 'en', label: 'English', locale: 'en_US',
    title: 'Tsubasa Ramen in Susukino, Sapporo | English Menu & Prices',
    description: 'Official English menu for Ajiichiban Tsubasa in Shin Ramen Yokocho, Susukino, Sapporo. Miso ramen, butter corn and ikura rice sets. Open 11am–3am; closed Mondays.',
    h1: 'Tsubasa ramen,\nin Susukino.', sub: 'English menu & prices',
    intro: 'Ajiichiban Tsubasa serves miso, soy sauce and salt ramen in Shin Ramen Yokocho, Sapporo. Join us for lunch or a late-night bowl in Susukino.',
    home: 'Official home', skip: 'Skip to content', menu: 'Menu', access: 'Hours & directions',
    viewMenu: 'See the full menu & prices', signatures: 'Three Tsubasa signatures',
    dishText: ['Soup simmered for three days, custom-made noodles and tender chashu pork. Our signature miso ramen.', 'Ramen topped with butter and corn. Choose miso, soy sauce or salt broth.', 'An ikura (salmon roe) rice bowl paired with a half-size ramen. A set for when you want both noodles and rice.'],
    dishTitles: ['Ultimate Miso Ramen', 'Butter Corn Ramen', 'Tsubasa Ramen Set'],
    flavors: ['Miso', 'Soy sauce', 'Salt'], groups: ['Miso ramen', 'Soy sauce ramen', 'Salt ramen', 'Sets, seasonal & half-size ramen', 'Extra noodles & toppings', 'Rice, gyoza & take-home ramen', 'Drinks'],
    all: 'Full menu & prices', priceNote: 'All prices are in Japanese yen. Please check seasonal menu availability at the restaurant.',
    visitTitle: 'From 11am to 3am.', hours: 'Open 11:00–03:00 the next day. Closed Mondays.',
    address: 'Shin Ramen Yokocho, No. 3 Green Building, Minami 4-jo Nishi 3-chome 1-1, Chuo-ku, Sapporo, Hokkaido',
    route: 'About a one-minute walk from Susukino intersection. Look for Ajiichiban Tsubasa (味一番つばさ) inside Shin Ramen Yokocho (新ラーメン横丁).',
    maps: 'Walking directions on Google Maps', call: 'Call the restaurant',
    notice: 'Holiday hours: open Monday, September 21, 2026; closed Thursday, September 24 instead.',
    qa: 'Before you visit',
    faqs: [
      ['Do you serve ramen other than miso?', 'Yes. Soy sauce and salt ramen are also available, including butter corn, chashu, green onion and kimchi options. See the menu above for prices.'],
      ['Are there smaller ramen portions or rice dishes?', 'The menu includes kids’ half-size miso, soy sauce and salt ramen, fried rice and plain rice. The Tsubasa set combines an ikura rice bowl with a half-size ramen.'],
      ['How late are you open?', 'Regular hours are 11:00am to 3:00am the following day, with Monday as the weekly closing day. Check official notices for holiday changes.'],
      ['Which menu languages are available?', 'The language links provide Japanese, English, Simplified Chinese and Korean menus with prices.'],
      ['What if I have an allergy or dietary restriction?', 'Please speak to the restaurant before ordering. Do not assume that a dish meets your dietary needs based only on its menu name.'],
    ],
    footer: 'A ramen counter in Shin Ramen Yokocho, Susukino, Sapporo.',
  },
  zh: {
    path: 'zh-hans/', lang: 'zh-Hans', label: '简体中文', locale: 'zh_CN',
    title: '味一番つばさ｜札幌薄野拉面・中文菜单与价格',
    description: '札幌薄野新拉面横丁「味一番つばさ」官方中文菜单。味噌拉面、黄油玉米拉面、鲑鱼籽盖饭配半份拉面。营业时间11:00至次日03:00，周一休息。查看价格与路线。',
    h1: '薄野的つばさ，\n拉面与菜单。', sub: '中文菜单与价格',
    intro: '味一番つばさ位于札幌薄野的新拉面横丁，提供味噌、酱油及盐味拉面。从午餐到深夜，都可以来这里享用一碗。',
    home: '官方网站首页', skip: '跳至正文', menu: '菜单', access: '营业时间与交通',
    viewMenu: '查看完整菜单与价格', signatures: 'つばさ的三款招牌',
    dishText: ['熬煮三天的汤底，搭配特制面条与软嫩叉烧。这是つばさ的招牌味噌拉面。', '拉面搭配黄油与玉米，可选择味噌、酱油或盐味汤底。', '鲑鱼籽盖饭搭配半份拉面的套餐。想同时品尝拉面和米饭时，可以选择这一款。'],
    dishTitles: ['究极味噌拉面', '黄油玉米拉面', 'TSUBASA拉面套餐'],
    flavors: ['味噌', '酱油', '盐味'], groups: ['味噌拉面', '酱油拉面', '盐味拉面', '套餐・期间限定・半份拉面', '加大份与加料', '米饭・煎饺・伴手礼拉面', '饮品'],
    all: '完整菜单与价格', priceNote: '价格均以日元标示。期间限定菜品的供应情况，请向店员确认。',
    visitTitle: '上午11点至次日凌晨3点。', hours: '营业时间 11:00〜次日03:00；每周一休息。',
    address: '北海道札幌市中央区南4条西3丁目1-1 第3グリーンビル 新ラーメン横丁',
    route: '从薄野十字路口步行约1分钟。请在新拉面横丁（新ラーメン横丁）内寻找「味一番つばさ」。',
    maps: '在Google地图查看步行路线', call: '致电店铺',
    notice: '节假日营业调整：2026年9月21日（周一）营业，改为9月24日（周四）休息。',
    qa: '来店前的常见问题',
    faqs: [
      ['除了味噌，还有其他口味吗？', '还有酱油和盐味拉面，包括黄油玉米、叉烧、葱花及泡菜等选择。价格请查看上方菜单。'],
      ['有小份拉面或米饭类菜品吗？', '有味噌、酱油、盐味的儿童半份拉面，也有炒饭和米饭。TSUBASA套餐包含鲑鱼籽盖饭与半份拉面。'],
      ['营业到几点？', '通常从11:00营业至次日03:00，每周一休息。节假日调整请查看官网通知。'],
      ['菜单有哪些语言？', '可通过语言链接查看日语、英语、简体中文和韩语菜单及价格。'],
      ['有食物过敏或饮食限制怎么办？', '请务必在点餐前向店员咨询。不要仅凭菜名判断菜品是否符合您的饮食要求。'],
    ],
    footer: '位于札幌薄野新拉面横丁的拉面店。',
  },
  ko: {
    path: 'ko/', lang: 'ko', label: '한국어', locale: 'ko_KR',
    title: '삿포로 스스키노 츠바사 라멘 | 한국어 메뉴·가격·영업시간',
    description: '삿포로 스스키노 신 라멘 요코초의 아지이치방 츠바사 공식 한국어 메뉴. 미소 라멘, 버터 콘 라멘, 이쿠라 덮밥과 하프 라멘 세트. 11:00~다음 날 03:00 영업, 월요일 휴무.',
    h1: '스스키노 츠바사,\n라멘 메뉴.', sub: '한국어 메뉴·가격',
    intro: '아지이치방 츠바사는 삿포로 스스키노의 신 라멘 요코초에서 미소·쇼유·시오 라멘을 선보입니다. 점심부터 늦은 밤까지 라멘을 즐겨 보세요.',
    home: '공식 홈페이지', skip: '본문 바로가기', menu: '메뉴', access: '영업시간·오시는 길',
    viewMenu: '전체 메뉴와 가격 보기', signatures: '츠바사의 대표 메뉴 세 가지',
    dishText: ['사흘 동안 끓인 국물과 특주 면, 부드러운 차슈를 담았습니다. 츠바사의 대표 미소 라멘입니다.', '버터와 옥수수를 더한 라멘입니다. 미소·쇼유·시오 중에서 고를 수 있습니다.', '이쿠라(연어알) 덮밥과 하프 라멘을 함께 즐기는 세트입니다. 면과 밥을 모두 먹고 싶을 때 골라 보세요.'],
    dishTitles: ['궁극의 미소 라멘', '버터 콘 라멘', '츠바사 라멘 세트'],
    flavors: ['미소', '쇼유', '시오'], groups: ['미소 라멘', '쇼유 라멘', '시오 라멘', '세트·기간 한정·하프 라멘', '곱빼기·토핑', '밥류·교자·기념품 라멘', '음료'],
    all: '전체 메뉴·가격', priceNote: '가격은 일본 엔화 기준입니다. 기간 한정 메뉴의 판매 여부는 매장에서 확인해 주세요.',
    visitTitle: '오전 11시부터, 다음 날 새벽 3시까지.', hours: '영업시간 11:00~다음 날 03:00 / 매주 월요일 휴무',
    address: '홋카이도 삿포로시 주오구 미나미 4조 니시 3초메 1-1 제3 그린빌딩 신 라멘 요코초',
    route: '스스키노 교차로에서 도보 약 1분. 신 라멘 요코초(新ラーメン横丁) 안의 아지이치방 츠바사(味一番つばさ)를 찾아주세요.',
    maps: 'Google 지도에서 도보 길찾기', call: '매장에 전화하기',
    notice: '연휴 영업 안내: 2026년 9월 21일(월)은 영업하며, 대신 9월 24일(목)에 쉽니다.',
    qa: '방문 전 자주 묻는 질문',
    faqs: [
      ['미소 외에 다른 라멘도 있나요?', '쇼유와 시오 라멘도 있습니다. 버터 콘, 차슈, 파, 김치 등의 종류와 가격은 위 메뉴에서 확인해 주세요.'],
      ['작은 라멘이나 밥류도 있나요?', '어린이 하프 라멘은 미소·쇼유·시오가 있습니다. 볶음밥과 공깃밥도 있으며, 츠바사 세트는 이쿠라 덮밥과 하프 라멘으로 구성됩니다.'],
      ['몇 시까지 영업하나요?', '평소 오전 11시부터 다음 날 새벽 3시까지 영업하며 월요일은 휴무입니다. 연휴 변경 사항은 공식 안내를 확인해 주세요.'],
      ['메뉴는 어떤 언어로 볼 수 있나요?', '언어 링크에서 일본어·영어·중국어 간체·한국어 메뉴와 가격을 볼 수 있습니다.'],
      ['알레르기나 식이 제한이 있으면 어떻게 하나요?', '주문 전에 반드시 매장에 문의해 주세요. 메뉴 이름만으로 식이 제한에 맞는 음식인지 판단하지 마세요.'],
    ],
    footer: '삿포로 스스키노 신 라멘 요코초의 라멘 가게.',
  },
};

export const editorial = [
  { path: 'ramen/', title: 'すすきのの味噌・バターコーン・いくら丼セット｜味一番つばさ',
    description: '札幌すすきの・新ラーメン横丁の味一番つばさ。三日間煮込んだスープの究極の味噌、3つの味から選べるバターコーン、いくら丼とハーフラーメンのセットをご紹介。公式価格とメニューへ。',
    h1: 'すすきので味わう、\nつばさの一杯。', sub: '味噌・バターコーン・いくら丼セット', image: 'ultimate-miso.webp',
    intro: '三日間煮込んだスープと特注麺。札幌・新ラーメン横丁で、四半世紀守ってきた味を。',
  },
  { path: 'access/', title: '営業時間・アクセス｜すすきの交差点から徒歩約1分｜味一番つばさ',
    description: '味一番つばさは札幌すすきの・新ラーメン横丁内。すすきの交差点から徒歩約1分、11:00〜翌3:00営業、月曜定休。住所・電話・徒歩ルートと深夜の来店案内を掲載。',
    h1: '昼の一杯も、\n深夜の〆も。', sub: '営業時間・アクセス', image: 'store-interior.webp',
    intro: 'すすきの交差点から徒歩約1分。新ラーメン横丁のカウンターで、お待ちしています。',
  },
];
